import type { Metadata } from "next";

import ThemeToggleButton from "MyApp/components/ThemeToggleButton";
import { ModalProvider } from "MyApp/contexts/ModalContext";
import DarkModeProvider from "MyApp/lib/dark-mode-provider";
import { ReactQueryProvider } from "MyApp/lib/react-query-provider";
import { Flip, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <DarkModeProvider>
            <div className="h-full min-h-screen overflow-y-auto text-black dark:text-white">
              <ModalProvider>
                {children}
                <ThemeToggleButton />
                <ToastContainer autoClose={1000} transition={Flip} theme={"colored"} />
              </ModalProvider>
            </div>
          </DarkModeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
